### ISSUE TITLE
Casting Exception in OreDictRecipeFilter

### ISSUE THREAD

**Issue by UntouchedWagons** [UntouchedWagons/Minecraft-Resource-Dumper#3]
java.lang.ClassCastException: untouchedwagons.minecraft.mcrd.api.resources.forge.OreDictionaryResource cannot be cast to untouchedwagons.minecraft.mcrd.api.resources.minecraft.ItemStackResource
        at untouchedwagons.minecraft.mcrd.api.recipes.filters.OreDictRecipeFilter.shouldFilterRecipe(OreDictRecipeFilter.java:51) ~[OreDictRecipeFilter.class:?]
        at untouchedwagons.minecraft.mcrd.commands.CollectDataCommand.func_184881_a(CollectDataCommand.java:136) ~[CollectDataCommand.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:92) [ClientCommandHandler.class:?]
        at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:437) [bft.class:?]
        at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:428) [bft.class:?]
        at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81) [bew.class:?]
        at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:571) [bft.class:?]
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:525) [bft.class:?]
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

As reported by Nyhal on [CurseForge](https://minecraft.curseforge.com/projects/minecraft-resource-dumper#c1)

**Comment by UntouchedWagons** [comment]
Fixed in 5fb6688, commit reference referred to wrong issue number. Whoops
